<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FoodSafeMontreal.Domain\FoodSafeMontreal.Domain.csproj" />
    <ProjectReference Include="..\FoodSafeMontreal.Application\FoodSafeMontreal.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
